名称 :建造

在 : [推 ,拉_请求 ]

工作 :

建造 :

运行 : $ { {矩阵.os } }

策略 :

故障-快速 :假

矩阵 :

操作系统 : [windows-最新 ]

构建类型 : [发布 ]

启用用户界面（_U） : [在 ]

包括 :

 -操作系统 :windows-最新

构建类型 :发布

启用用户界面（_U） :在

步骤 :

 -使用 :行动/签出@v3

具有 :

 子模块 :“递归”

 -名称 : 卡切

使用 : 手套/ ccache-action@v1

如果 :跑步者.os==“Linux”

具有 :

钥匙 : $ { {矩阵.os } } -$ { {matrix.enable_ui矩阵 } }

 -使用 :西恩米德利奇/gha-setup-ninja@master

 -使用 : 伊拉米/ msvc-dev-cmd@v1

如果 :runner.os ==“Windows”

 -名称 :再进行

壳 :猛击

运行 : |

if [[ "${{ runner.os }}" == "Linux" ]] ; then

sudo apt-get更新-qq

sudo apt-get安装-y\

libx11-dev libxcursor-dev libxi-dev

fi（菲涅耳）

 -名称 :生成生成文件

壳 :猛击

运行 : |

if [[ "${{ runner.os }}" == "Windows" ]] ; then

export enable_ccache=off

其他的

export enable_ccache=on

fi（菲涅耳）

卷曲-Lhttps://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip--输出skia.zip

 7z x滑雪板拉链

cmake-S型-B型-G忍者\

-DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \

-DENABLE_UI=${{ matrix.enable_ui }} \

-DENABLE_CCACHE=$enable_ccache \

-DLAF_BACKEND=skia \

-DSKIA_DIR=./skia \

-DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \

-DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib

 -名称 :正在编译

壳 :猛击

运行 : |

cd构建和忍者

 -使用 :行动/上传artifact@v3

具有 :

名称 : 插入

路径 : |

D： /a/asprite/asprite/build/bin/data

D： /a/asprite/asprite/build/bin/aseprite.exe作者：独立游戏杂货铺 https://www.bilibili.com/read/cv27083106/■胆汁
